### ISSUE TITLE
Progress monitor throws exception on sftp download and upload

### ISSUE THREAD

**Issue by ronpetit** [shaqian/flutter_ssh#12]
On SshPlugin.java, at line 469, the progress monitor used to monitor sftp download (and upload too but in another line), throws an exception over Android with the error "No such file" (which is not true), removing the progress monitor fix the issue, but is not the point, that was a quick fix for me that I was not going to use that feature.

I only tested it over Android using a Nexus 5X, flutter 1.7.8 and ssh 0.0.4

**Comment by shaqian** [comment]
This is fixed 0.0.5. Archiving the issue.

Thanks,
Qian
