### ISSUE TITLE
Unable to connect to ftp server

### ISSUE THREAD

**Issue by sudamchole** [shaqian/flutter_ssh#16]
I am getting this error-
**E/SshPlugin( 7624): Connection failed: connection is closed by foreign host
I/flutter ( 7624): Error: connection_failure**

I have tried from file zila it is connecting but from android device it gives me this error.
using port 21

**Comment by shaqian** [comment]
Hi sudamchole,

This plugin wraps JSch on Android. According to the discussion below, JSch doesn't support FTP.
https://stackoverflow.com/questions/7393545/how-can-i-access-an-ftp-server-with-jsch

Thanks,
Qian
