### ISSUE TITLE
PlatformException(connection_failure, java.lang.ClassNotFoundException: com.jcraft.jsch.jce.Random, null)

### ISSUE THREAD

**Issue by nisadrahman** [shaqian/flutter_ssh#35]
PlatformException(connection_failure, java.lang.ClassNotFoundException: com.jcraft.jsch.jce.Random, null)

An exception occurs when trying to connect on release APK, works fine on debug.

**Comment by nisadrahman** [comment]
flutter build apk --no-shrink
No shrink fixes the problem. But, what if someone needs shrink?

**Comment by english-aha-center** [comment]
> flutter build apk --no-shrink
> No shrink fixes the problem. But, what if someone needs shrink?

I had the same issue!! 
After a days of searching... you saved me!!

Thanks and I hope this is fixed soon.

**Comment by nisadrahman** [comment]
Considering there is a solution, therefore closing the issue.
