### ISSUE TITLE
'ssh/SshPlugin.h' file not found when build iOS

### ISSUE THREAD

**Issue by ch331917692** [shaqian/flutter_ssh#4]
`'ssh/SshPlugin.h' file not found` in `GeneratedPluginRegistrant.m` file  when build iOS project

**Comment by shaqian** [comment]
Looks similar to https://github.com/flutter/flutter/issues/15152
Are you using a Swift based project? If yes, can you try Objective-C?

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
