### ISSUE TITLE
SSHClient disconnect never completes

### ISSUE THREAD

**Issue by pbaker5** [shaqian/flutter_ssh#5]
On both iOS and Android, disconnect never completes. 

This happens even for a simple use case of:
 
SSHClient _client;
await _client.connect();
await _client.disconnect();

I'm on Flutter Channel dev, v1.1.8, on Mac OS X 10.14.3.

**Comment by shaqian** [comment]
Hi, 

Sorry for the late reply. Is this resolved by your PR? I merged it in v0.0.3.

Thanks,
Qian

**Comment by pbaker5** [comment]
No.

**Comment by DemonShi** [comment]
+1 The disconnect never happens.

**Comment by shaqian** [comment]
Thank you for the feedback. 

I forgot that disconnect method doesn't return result from native code. 
https://github.com/shaqian/flutter_ssh/blob/master/ios/Classes/SshPlugin.m#L455

The dart code should not be async. I will fix this in next version.

**Comment by ronpetit** [comment]
Any updates on this? @shaqian I don't like to just leave it there without disconnection.

I don't understand that .m file, I would like to help

**Comment by SunLongbri** [comment]
I never connect server by SFTP , and the ip , host ,username,pass are all correct.Some tiem later, the app  creshed and exit.

**Comment by shaqian** [comment]
Sorry for the delay. The fix is in v0.0.4. 

Thanks,
Qian
