### ISSUE TITLE
SFTP - Connect Hangs

### ISSUE THREAD

**Issue by track02** [shaqian/flutter_ssh#9]
I'm interested in your library and  trying to run the example to test SFTP access - however after calling `connect()` the system just seems to hang and nothing resolves

Is this due to my host being an IP Address? And If so is there a correct way to do this?

```  Future<void> onClickSFTP() async {
    var client = new SSHClient(
      host: "192.168.10.5",
      port: 21,
      username: "user",
      passwordOrKey: "pass",
    );

    try {
      print("Attempting connection");
      String result = await client.connect(); //Never get past here!
      if (result == "session_connected") {
        result = await client.connectSFTP();
        if (result == "sftp_connected") {`
        ...

```

**Comment by shaqian** [comment]
Hi,

Are you running it on iOS or Android? Can you try to debug in XCode or Android Studio and see where it got stuck?

The IP address 192.168.10.5 is internal. Make sure your device in the same internal network.

**Comment by track02** [comment]
This was running on an Android device which was on the same internal network as the SFTP server
I'll hook it up to Android Studio and get back with some more info

**Comment by shaqian** [comment]
Archiving the thread. Feel free to reopen if the issue persists.

Thanks,
Qian
